### ISSUE TITLE
(0, next_1.default) is not a function error

### ISSUE THREAD

**Issue by kkuk6-dev628** [kkuk6-dev628/EZWx_2.0#349]
When I update nextjs from 13.2.4 to 13.4.17, this error occurred in createServer function of view.service.ts
